import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

// ============================================================
// Read Aloud Prompt Audio Generator — Production V1
// ============================================================
//
// PURPOSE
// -------
// Generate the authentic Read Aloud PROMPT audio set.
//
// IMPORTANT
// ---------
// This generator creates PROMPT recordings only.
//
// Student-response recordings are generated by:
//   scripts/generateReadAloudStudentResponseAudio.mjs
//
// Student responses are stored in:
//   generated-audio/read-aloud/student-responses-v1
//
// Read Aloud prompts are stored separately in:
//   generated-audio/read-aloud/prompts-v1
//
// Output filename format:
//   exercise-001-prompt-achernar.mp3
//   exercise-002-prompt-orus.mp3
//   ...
//
// ============================================================


// ============================================================
// Google Cloud / Gemini TTS configuration
// ============================================================

const PROJECT_ID = "gen-lang-client-0294792757";

const MODEL = "gemini-2.5-flash-tts";

const LANGUAGE_CODE = "en-US";

const SPEAKING_RATE = 1.0;


// ============================================================
// Calibration source
// ============================================================
//
// The Read Aloud prompt stimulus is stored in:
//
//   promptText
//
// inside:
//
//   READ_ALOUD_CALIBRATION_EXERCISES
//
// in exerciseBank.ts.
//
// ============================================================

const CALIBRATION_FILE = path.resolve(
  "src/masterTeacher/constants/exerciseBank.ts"
);


// ============================================================
// Prompt audio output folder
// ============================================================
//
// IMPORTANT:
// This is deliberately different from the student-response
// folder.
//
// Student responses:
//   generated-audio/read-aloud/student-responses-v1
//
// Prompt recordings:
//   generated-audio/read-aloud/prompts-v1
//
// ============================================================

const OUTPUT_DIR = path.resolve(
  "generated-audio/read-aloud/prompts-v1"
);


// ============================================================
// Expected calibration exercise count
// ============================================================

const EXPECTED_EXERCISE_COUNT = 100;


// ============================================================
// Approved voice rotation
// ============================================================
//
// 1. Achernar
// 2. Orus
// 3. Leda
// 4. Puck
// 5. Sulafat
// 6. Iapetus
//
// Then repeat.
//
// Exercise 1  → Achernar
// Exercise 2  → Orus
// Exercise 3  → Leda
// Exercise 4  → Puck
// Exercise 5  → Sulafat
// Exercise 6  → Iapetus
// Exercise 7  → Achernar
// ...
//
// ============================================================

const VOICES = [
  "Achernar",
  "Orus",
  "Leda",
  "Puck",
  "Sulafat",
  "Iapetus",
];


// ============================================================
// Validated TTS instruction
// ============================================================
//
// This is deliberately short.
//
// The promptText itself is the exact stimulus that should be
// spoken. The instruction tells Gemini to speak that text
// exactly and not add explanatory language.
//
// ============================================================

const TTS_PROMPT =
  "Say the following exactly as written. Do not add, remove, repeat, paraphrase, or change any words. Use a natural conversational speaking style.";


// ============================================================
// Request throttling / retry configuration
// ============================================================

const REQUEST_DELAY_MS = 3000;

const MAX_429_RETRIES = 5;

const INITIAL_429_RETRY_DELAY_MS = 15000;


// ============================================================
// Google Cloud Text-to-Speech endpoint
// ============================================================

const TTS_ENDPOINT =
  "https://texttospeech.googleapis.com/v1/text:synthesize";


// ============================================================
// Command-line arguments
// ============================================================
//
// Examples:
//
// Generate Exercises 1–6:
//
//   node scripts/generateReadAloudPromptAudio.mjs --start 1 --end 6
//
// Regenerate Exercises 1–6:
//
//   node scripts/generateReadAloudPromptAudio.mjs --start 1 --end 6 --force
//
// Generate all 100:
//
//   node scripts/generateReadAloudPromptAudio.mjs --start 1 --end 100
//
// Regenerate all 100:
//
//   node scripts/generateReadAloudPromptAudio.mjs --start 1 --end 100 --force
//
// ============================================================

const args = process.argv.slice(2);


function getArgValue(name) {
  const index = args.indexOf(name);

  if (index === -1) {
    return null;
  }

  return args[index + 1] ?? null;
}


function hasFlag(name) {
  return args.includes(name);
}


const requestedStart = getArgValue("--start");

const requestedEnd = getArgValue("--end");

const force = hasFlag("--force");


const startExercise = requestedStart
  ? Number.parseInt(requestedStart, 10)
  : 1;


const endExercise = requestedEnd
  ? Number.parseInt(requestedEnd, 10)
  : EXPECTED_EXERCISE_COUNT;


// ============================================================
// Validate requested range
// ============================================================

if (
  !Number.isInteger(startExercise) ||
  !Number.isInteger(endExercise) ||
  startExercise < 1 ||
  endExercise < startExercise ||
  endExercise > EXPECTED_EXERCISE_COUNT
) {
  throw new Error(
    `Invalid exercise range. Use --start N --end N where 1 <= N <= ${EXPECTED_EXERCISE_COUNT} and start <= end.`
  );
}


// ============================================================
// Helpers
// ============================================================

function fail(message) {
  throw new Error(message);
}


function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}


// ============================================================
// Google ADC access token
// ============================================================

function getAccessToken() {
  try {
    return execFileSync(
      "cmd.exe",
      [
        "/c",
        "gcloud",
        "auth",
        "application-default",
        "print-access-token",
      ],
      {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
      }
    ).trim();
  } catch (error) {
    console.error("");

    console.error(
      "DEBUG: Node could not obtain the Google ADC token."
    );

    console.error(
      "Error code:",
      error?.code
    );

    console.error(
      "Error message:",
      error?.message
    );

    console.error(
      "Error stderr:",
      error?.stderr?.toString?.()
    );

    console.error(
      "Error stdout:",
      error?.stdout?.toString?.()
    );

    throw new Error(
      "Could not obtain an ADC access token. Run: gcloud auth application-default login"
    );
  }
}


// ============================================================
// Decode a TypeScript string literal
// ============================================================

function decodeString(value) {
  try {
    return JSON.parse(`"${value}"`);
  } catch {
    return value
      .replace(/\\"/g, '"')
      .replace(/\\\\/g, "\\");
  }
}


// ============================================================
// Extract Read Aloud calibration exercises
// ============================================================
//
// We deliberately isolate the exact
// READ_ALOUD_CALIBRATION_EXERCISES array.
//
// exerciseBank.ts contains many other exercise collections,
// so the entire file is not scanned blindly.
//
// ============================================================

function extractReadAloudExercises(source) {
  const declaration =
    "export const READ_ALOUD_CALIBRATION_EXERCISES = [";

  const arrayStart = source.indexOf(declaration);

  if (arrayStart === -1) {
    fail(
      `Could not find ${declaration} in ${CALIBRATION_FILE}.`
    );
  }


  const arrayEnd = source.indexOf(
    "\n];",
    arrayStart + declaration.length
  );

  if (arrayEnd === -1) {
    fail(
      "Could not find the end of READ_ALOUD_CALIBRATION_EXERCISES."
    );
  }


  const calibrationSource = source.slice(
    arrayStart + declaration.length,
    arrayEnd
  );


  const indexMatches = [
    ...calibrationSource.matchAll(
      /(?:^|\n)\s*exerciseIndex\s*:\s*(\d+)\s*,/g
    ),
  ];


  if (
    indexMatches.length !==
    EXPECTED_EXERCISE_COUNT
  ) {
    fail(
      `Expected exactly ${EXPECTED_EXERCISE_COUNT} Read Aloud exerciseIndex entries, but found ${indexMatches.length}. No audio will be generated.`
    );
  }


  const exercises = [];


  for (
    let i = 0;
    i < indexMatches.length;
    i += 1
  ) {
    const match = indexMatches[i];

    const exerciseIndex =
      Number.parseInt(match[1], 10);


    const blockStart = match.index;


    const blockEnd =
      i + 1 < indexMatches.length
        ? indexMatches[i + 1].index
        : calibrationSource.length;


    const block = calibrationSource.slice(
      blockStart,
      blockEnd
    );


    const promptTextMatch = block.match(
      /promptText\s*:\s*"((?:\\.|[^"\\])*)"/
    );


    if (!promptTextMatch) {
      fail(
        `Exercise ${exerciseIndex}: promptText was not found. No audio will be generated.`
      );
    }


    exercises.push({
      exerciseIndex,
      promptText: decodeString(
        promptTextMatch[1]
      ),
    });
  }


  return exercises.sort(
    (a, b) =>
      a.exerciseIndex -
      b.exerciseIndex
  );
}


// ============================================================
// Validate all Read Aloud exercises
// ============================================================

function validateExercises(exercises) {
  if (
    exercises.length !==
    EXPECTED_EXERCISE_COUNT
  ) {
    fail(
      `Expected exactly ${EXPECTED_EXERCISE_COUNT} Read Aloud calibration exercises, but extracted ${exercises.length}. No audio will be generated.`
    );
  }


  for (
    let i = 0;
    i < exercises.length;
    i += 1
  ) {
    const expectedIndex = i + 1;

    const exercise = exercises[i];


    if (
      exercise.exerciseIndex !==
      expectedIndex
    ) {
      fail(
        `Exercise numbering error: expected ${expectedIndex}, found ${exercise.exerciseIndex}. No audio will be generated.`
      );
    }


    if (
      !exercise.promptText.trim()
    ) {
      fail(
        `Exercise ${expectedIndex} has an empty promptText. No audio will be generated.`
      );
    }
  }
}


// ============================================================
// Voice rotation
// ============================================================

function getVoiceForExercise(
  exerciseIndex
) {
  return VOICES[
    (exerciseIndex - 1) %
      VOICES.length
  ];
}


// ============================================================
// Filename
// ============================================================
//
// IMPORTANT:
//
// These names deliberately match the established Read Aloud
// prompt naming convention:
//
//   exercise-001-prompt-achernar.mp3
//   exercise-002-prompt-orus.mp3
//
// ============================================================

function getOutputFilename(
  exerciseIndex,
  voice
) {
  return (
    `exercise-${String(exerciseIndex).padStart(3, "0")}` +
    `-prompt-${voice.toLowerCase()}.mp3`
  );
}


function getOutputPath(
  exerciseIndex,
  voice
) {
  return path.join(
    OUTPUT_DIR,
    getOutputFilename(
      exerciseIndex,
      voice
    )
  );
}


// ============================================================
// Gemini TTS synthesis
// ============================================================

async function synthesizeSpeech({
  accessToken,
  text,
  voiceName,
  exerciseIndex,
}) {
  const requestBody = {
    input: {
      prompt: TTS_PROMPT,
      text,
    },

    voice: {
      languageCode: LANGUAGE_CODE,
      name: voiceName,
      modelName: MODEL,
    },

    audioConfig: {
      audioEncoding: "MP3",
      speakingRate: SPEAKING_RATE,
    },
  };


  for (
    let attempt = 0;
    attempt <= MAX_429_RETRIES;
    attempt += 1
  ) {
    try {
      const response = await fetch(
        TTS_ENDPOINT,
        {
          method: "POST",

          headers: {
            Authorization:
              `Bearer ${accessToken}`,

            "Content-Type":
              "application/json",

            "x-goog-user-project":
              PROJECT_ID,
          },

          body: JSON.stringify(
            requestBody
          ),
        }
      );


      if (response.ok) {
        const data =
          await response.json();


        if (!data.audioContent) {
          throw new Error(
            "Google TTS returned a successful response but no audioContent."
          );
        }


        return Buffer.from(
          data.audioContent,
          "base64"
        );
      }


      const responseText =
        await response.text();


      const retryableStatuses =
        new Set([
          429,
          500,
          502,
          503,
          504,
        ]);


      if (
        retryableStatuses.has(
          response.status
        ) &&
        attempt < MAX_429_RETRIES
      ) {
        const retryDelay =
          INITIAL_429_RETRY_DELAY_MS *
          Math.pow(2, attempt);


        console.warn(
          `  Google TTS returned HTTP ${response.status}. Retrying in ${Math.round(
            retryDelay / 1000
          )} seconds...`
        );


        await sleep(
          retryDelay
        );

        continue;
      }


      throw new Error(
        `Exercise ${exerciseIndex}: TTS request failed with HTTP ${response.status}: ${responseText}`
      );

    } catch (error) {
      const message =
        String(
          error?.message ??
          error
        );


      const retryableNetworkError =
        message.includes(
          "fetch failed"
        ) ||
        message.includes(
          "ECONNRESET"
        ) ||
        message.includes(
          "ETIMEDOUT"
        ) ||
        message.includes(
          "socket"
        );


      if (
        retryableNetworkError &&
        attempt < MAX_429_RETRIES
      ) {
        const retryDelay =
          INITIAL_429_RETRY_DELAY_MS *
          Math.pow(2, attempt);


        console.warn(
          `  Temporary network error. Retrying in ${Math.round(
            retryDelay / 1000
          )} seconds...`
        );


        await sleep(
          retryDelay
        );

        continue;
      }


      throw error;
    }
  }


  throw new Error(
    `Exercise ${exerciseIndex}: TTS synthesis failed after all retry attempts.`
  );
}


// ============================================================
// Main
// ============================================================

async function main() {
  console.log("");

  console.log(
    "============================================================"
  );

  console.log(
    " Read Aloud Prompt Audio Generator"
  );

  console.log(
    "============================================================"
  );

  console.log("");


  console.log(
    `Calibration file: ${CALIBRATION_FILE}`
  );

  console.log(
    `Output directory:  ${OUTPUT_DIR}`
  );

  console.log(
    `Google project:    ${PROJECT_ID}`
  );

  console.log(
    `TTS model:         ${MODEL}`
  );

  console.log(
    `Language:          ${LANGUAGE_CODE}`
  );

  console.log(
    `Speaking rate:     ${SPEAKING_RATE}`
  );

  console.log("");


  console.log(
    `Read Aloud exercise range: ${startExercise}-${endExercise}`
  );

  console.log(
    `Force regeneration: ${force ? "YES" : "NO"}`
  );

  console.log("");


  console.log(
    "Voice rotation:"
  );


  VOICES.forEach(
    (voice, index) => {
      console.log(
        `  ${index + 1}. ${voice}`
      );
    }
  );


  console.log("");

  console.log(
    "TTS instruction:"
  );

  console.log(
    `  ${TTS_PROMPT}`
  );

  console.log("");


  // ----------------------------------------------------------
  // Read calibration file
  // ----------------------------------------------------------

  const source =
    fs.readFileSync(
      CALIBRATION_FILE,
      "utf8"
    );


  // ----------------------------------------------------------
  // Extract and validate all exercises
  // ----------------------------------------------------------

  const exercises =
    extractReadAloudExercises(
      source
    );


  validateExercises(
    exercises
  );


  console.log(
    `Read Aloud exercises found: ${exercises.length}`
  );

  console.log(
    `Read Aloud exercises validated: 1-${EXPECTED_EXERCISE_COUNT}`
  );

  console.log("");


  // ----------------------------------------------------------
  // Select requested range
  // ----------------------------------------------------------

  const selectedExercises =
    exercises.filter(
      (exercise) =>
        exercise.exerciseIndex >=
          startExercise &&
        exercise.exerciseIndex <=
          endExercise
    );


  if (
    selectedExercises.length === 0
  ) {
    fail(
      "No exercises were selected for generation."
    );
  }


  console.log(
    `Exercises selected for generation: ${selectedExercises.length}`
  );

  console.log("");


  // ----------------------------------------------------------
  // Display selected prompt source text
  // ----------------------------------------------------------

  console.log(
    "Selected prompt source text:"
  );


  for (
    const exercise of selectedExercises
  ) {
    const voice =
      getVoiceForExercise(
        exercise.exerciseIndex
      );


    console.log(
      `  Exercise ${exercise.exerciseIndex} → ${voice}`
    );

    console.log(
      `    ${exercise.promptText}`
    );
  }


  console.log("");


  // ----------------------------------------------------------
  // Ensure output directory exists
  // ----------------------------------------------------------

  fs.mkdirSync(
    OUTPUT_DIR,
    {
      recursive: true,
    }
  );


  // ----------------------------------------------------------
  // Obtain Google ADC token
  // ----------------------------------------------------------

  const accessToken =
    getAccessToken();


  if (!accessToken) {
    fail(
      "Google ADC returned an empty access token."
    );
  }


  console.log(
    "Google ADC access token obtained successfully."
  );

  console.log("");


  // ----------------------------------------------------------
  // Generation report
  // ----------------------------------------------------------

  const report = {
    generatedAt:
      new Date().toISOString(),

    projectId:
      PROJECT_ID,

    model:
      MODEL,

    languageCode:
      LANGUAGE_CODE,

    speakingRate:
      SPEAKING_RATE,

    voices:
      VOICES,

    requestDelayMs:
      REQUEST_DELAY_MS,

    max429Retries:
      MAX_429_RETRIES,

    initial429RetryDelayMs:
      INITIAL_429_RETRY_DELAY_MS,

    audioType:
      "prompt",

    calibrationFile:
      CALIBRATION_FILE,

    outputDirectory:
      OUTPUT_DIR,

    ttsPrompt:
      TTS_PROMPT,

    exercisesRequested:
      selectedExercises.length,

    generated:
      0,

    skipped:
      0,

    failed:
      0,

    files: [],
  };


  // ----------------------------------------------------------
  // Generate selected exercises
  // ----------------------------------------------------------

  for (
    const exercise of selectedExercises
  ) {
    const exerciseIndex =
      exercise.exerciseIndex;


    const voice =
      getVoiceForExercise(
        exerciseIndex
      );


    const filename =
      getOutputFilename(
        exerciseIndex,
        voice
      );


    const outputPath =
      getOutputPath(
        exerciseIndex,
        voice
      );


    console.log(
      `Exercise ${String(exerciseIndex).padStart(3, "0")} → ${voice}`
    );

    console.log(
      `  Prompt: ${exercise.promptText}`
    );

    console.log(
      `  Output: ${filename}`
    );


    // --------------------------------------------------------
    // Existing file handling
    // --------------------------------------------------------

    if (
      fs.existsSync(
        outputPath
      ) &&
      !force
    ) {
      const existingStats =
        fs.statSync(
          outputPath
        );


      console.log(
        "  Status: SKIPPED — file already exists."
      );

      console.log("");


      report.skipped += 1;


      report.files.push({
        exerciseIndex,
        voice,
        promptText:
          exercise.promptText,
        filename,
        status:
          "skipped-existing",
        sizeBytes:
          existingStats.size,
        error:
          null,
      });


      continue;
    }


    try {
      // ------------------------------------------------------
      // Generate MP3
      // ------------------------------------------------------

      const audioBuffer =
        await synthesizeSpeech({
          accessToken,
          text:
            exercise.promptText,
          voiceName:
            voice,
          exerciseIndex,
        });


      // ------------------------------------------------------
      // Write MP3
      // ------------------------------------------------------

      fs.writeFileSync(
        outputPath,
        audioBuffer
      );


      const stats =
        fs.statSync(
          outputPath
        );


      console.log(
        `  Status: GENERATED (${stats.size} bytes)`
      );

      console.log("");


      report.generated += 1;


      report.files.push({
        exerciseIndex,
        voice,
        promptText:
          exercise.promptText,
        filename,
        status:
          "generated",
        sizeBytes:
          stats.size,
        error:
          null,
      });

    } catch (error) {
      console.error(
        `  Status: FAILED — ${error?.message ?? error}`
      );

      console.log("");


      report.failed += 1;


      report.files.push({
        exerciseIndex,
        voice,
        promptText:
          exercise.promptText,
        filename,
        status:
          "failed",
        sizeBytes:
          null,
        error:
          String(
            error?.message ??
            error
          ),
      });
    }


    // --------------------------------------------------------
    // Delay between requests
    // --------------------------------------------------------

    if (
      exerciseIndex !==
      selectedExercises[
        selectedExercises.length - 1
      ].exerciseIndex
    ) {
      await sleep(
        REQUEST_DELAY_MS
      );
    }
  }


  // ----------------------------------------------------------
  // Save generation report
  // ----------------------------------------------------------

  const reportPath =
    path.join(
      OUTPUT_DIR,
      "generation-report.json"
    );


  fs.writeFileSync(
    reportPath,
    JSON.stringify(
      report,
      null,
      2
    ),
    "utf8"
  );


  // ----------------------------------------------------------
  // Final summary
  // ----------------------------------------------------------

  console.log("");

  console.log(
    "============================================================"
  );

  console.log(
    " Generation complete"
  );

  console.log(
    "============================================================"
  );

  console.log("");

  console.log(
    `Requested: ${report.exercisesRequested}`
  );

  console.log(
    `Generated: ${report.generated}`
  );

  console.log(
    `Skipped:   ${report.skipped}`
  );

  console.log(
    `Failed:    ${report.failed}`
  );

  console.log("");

  console.log(
    `Output directory: ${OUTPUT_DIR}`
  );

  console.log(
    `Report:           ${reportPath}`
  );

  console.log("");


  if (
    report.failed > 0
  ) {
    process.exitCode = 1;
  }
}


// ============================================================
// Run
// ============================================================

main().catch(
  (error) => {
    console.error("");

    console.error(
      "============================================================"
    );

    console.error(
      " Read Aloud Prompt Audio Generator FAILED"
    );

    console.error(
      "============================================================"
    );

    console.error("");

    console.error(
      error?.stack ??
      error?.message ??
      error
    );

    console.error("");

    process.exitCode = 1;
  }
);